### ISSUE TITLE
Can this be used for Teams

### ISSUE THREAD

**Issue by sarangvyas** [studio24/bitbucket-bulk-add-hook#5]
@WillPresley  @simonrjones   The current implementation works for account very well. However i want to update the webhooks for a team. Is this possible using the script ?

**Comment by WillPresley** [comment]
[**@sarangvyas**](https://github.com/sarangvyas) commented on [Mar 6, 2016, 11:33 PM EST](https://github.com/studio24/bitbucket-bulk-add-hook/issues/5#issue-138885269):

> [@WillPresley](https://github.com/WillPresley)  [@simonrjones](https://github.com/simonrjones)   The current implementation works for account very well. However i want to update the webhooks for a team. Is this possible using the script ?

After BitBucket updated their Hooks to Webhooks and extended the API, I went looking for a new solution. I found this: https://github.com/InterativaDigital/bitbucket-bulk-add-webhook But it was not really usable for teams. My fork here: https://github.com/WillPresley/bitbucket-bulk-add-webhook has commits made to have the script work with team information. Give it a try and let me know **on my repo** if it's working for you.

**Comment by sarangvyas** [comment]
Sure. I will give it a try and let you know. Thanks for your help !

**Comment by WillPresley** [comment]
Feel free to close this if you want to @simonrjones. @sarangvyas tested the different version I linked to for using with teams (and using the new webhooks) and says it works for him as well.

**Comment by simonrjones** [comment]
thanks for the comments Will, I'll close this now
